# Generated by Django 5.1.4 on 2024-12-29 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("borrowings", "0003_alter_borrowing_book_alter_borrowing_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="correct_return_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__lte", models.F("expected_return_date")),
                    ("actual_return_date__lt", models.F("borrow_date")),
                    _connector="OR",
                ),
                name="correct_return_date",
            ),
        ),
    ]
