# Generated by Django 5.1.4 on 2024-12-29 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("borrowings", "0004_remove_borrowing_correct_return_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="expected_return_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="correct_return_date",
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__lte", models.F("expected_return_date"))
                ),
                name="correct_return_date",
            ),
        ),
    ]
